[project]
name = "daily-arxiv"
version = "0.1.0"
description = "Daily crawl arXiv papers and use LLMs to summarize them"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.1.3"
]
license = "Apache-2.0"
